/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DayYearRouteImport } from './routes/day/[year]'
import { Route as ApiDayRatingsRouteImport } from './routes/api/day-ratings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DayYearRoute = DayYearRouteImport.update({
  id: '/day/year',
  path: '/day/year',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDayRatingsRoute = ApiDayRatingsRouteImport.update({
  id: '/api/day-ratings',
  path: '/api/day-ratings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/day-ratings': typeof ApiDayRatingsRoute
  '/day/year': typeof DayYearRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/day-ratings': typeof ApiDayRatingsRoute
  '/day/year': typeof DayYearRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/day-ratings': typeof ApiDayRatingsRoute
  '/day/year': typeof DayYearRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/day-ratings' | '/day/year'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/day-ratings' | '/day/year'
  id: '__root__' | '/' | '/api/day-ratings' | '/day/year'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDayRatingsRoute: typeof ApiDayRatingsRoute
  DayYearRoute: typeof DayYearRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day/year': {
      id: '/day/year'
      path: '/day/year'
      fullPath: '/day/year'
      preLoaderRoute: typeof DayYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/day-ratings': {
      id: '/api/day-ratings'
      path: '/api/day-ratings'
      fullPath: '/api/day-ratings'
      preLoaderRoute: typeof ApiDayRatingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDayRatingsRoute: ApiDayRatingsRoute,
  DayYearRoute: DayYearRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
